### ISSUE TITLE
Python3.9 User get error "AttributeError: module 'time' has no attribute 'clock'"

### ISSUE THREAD

**Issue by wkc41511** [cisagov/log4j-scanner#11]
if u got this "AttributeError: module 'time' has no attribute 'clock'"

Try this

vim /usr/local/lib/python3.9/site-packages/Crypto/Random/_UserFriendlyRNG.py

line 77 : "t = time.clock()" to "t = time.perf_counter()"

**Comment by wkc41511** [comment]
if got this "ModuleNotFoundError: No module named 'Crypto'"

Try this :
pip3.9 install pycrypto

**Comment by sabretus** [comment]
This helped me

```
pip3 uninstall PyCrypto
pip3 install -U PyCryptodome
```

**Comment by genericcontributor** [comment]
Thank you for the references.
