### ISSUE TITLE
ddnsserver.py: error: unrecognized arguments: 53

### ISSUE THREAD

**Issue by shivammusic** [cisagov/log4j-scanner#15]
command:
python3 ddnsserver.py --udp 53

o/p:

usage: ddnsserver.py [-h] [--port PORT] [--tcp] [--udp]
ddnsserver.py: error: unrecognized arguments: 53

<img width="739" alt="Screenshot 2021-12-23 at 11 13 36 PM" src="https://user-images.githubusercontent.com/41016630/147275505-8c282548-f21e-4eda-bdf4-8c676d438149.png">

**Comment by KyleEvers** [comment]
Hi @shivammusic, looks like your intended command line arguments should be `python3 ddnsserver.py --port 53 --udp` and `python3 ddnsserver.py --port 1337 --tcp` respectively where `--udp` or `--tcp` are just a boolean arguments. 

Hope this helps!

**Comment by shivammusic** [comment]
hi @KyleEvers 

i run `python3 ddnsserver.py --port 53 --udp`

and got 

```
Starting nameserver...
Traceback (most recent call last):
  File "ddnsserver.py", line 175, in <module>
    main()
  File "ddnsserver.py", line 153, in main
    if args.udp: servers.append(socketserver.ThreadingUDPServer(('', args.port), UDPRequestHandler))
  File "/usr/lib/python3.8/socketserver.py", line 452, in __init__
    self.server_bind()
  File "/usr/lib/python3.8/socketserver.py", line 466, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use
reconpad2@root:/home/ubuntu/log4j-scanner/dns# 
```
Then i found run `ps -fA | grep python` to grep running process and killed them. But still getting this error.

<img width="933" alt="Screenshot 2021-12-24 at 12 18 16 AM" src="https://user-images.githubusercontent.com/41016630/147281214-67c6603e-d5bb-448b-b5ad-c462c557edaf.png">

**Comment by global4g** [comment]
@shivammusic You may have to open up port 53 on your system. Most likely its in use already. 
sudo lsof -i :53 to check

**Comment by genericcontributor** [comment]
The typo in the command was fixed. Thank you. @KyleEvers 

@shivammusic , it does seem like you're using the port. It also appears like you're on a ubuntu box. Try these steps if you're still having issues.

 
https://www.linuxuprising.com/2020/07/ubuntu-how-to-free-up-port-53-used-by.html
