### ISSUE TITLE
Getting below error

### ISSUE THREAD

**Issue by PrestonD88** [cisagov/log4j-scanner#19]
python3 log4j-scan.py -h
  File "log4j-scan.py", line 148
    fuzzing_headers["Referer"] = f'https://{fuzzing_headers["Referer"]}'
                                                                       ^
SyntaxError: invalid syntax

**Comment by PrestonD88** [comment]
Got fixed with higher version of Python

**Comment by genericcontributor** [comment]
Thanks!
