### ISSUE TITLE
Connection timeout during standard execution

### ISSUE THREAD

**Issue by pablosnt** [cisagov/log4j-scanner#55]
# 🐛 Summary #

What's wrong? Please be specific.

Connection timeout error during log4j-scanner execution. Of course, I have connectivity with the target.

1. Execute: `python3 log4-scanner/log4j-scan.py -u https://host`

## Any helpful log output or screenshots ##

![Screenshot_2022-08-31_09_23_50](https://user-images.githubusercontent.com/69458381/187618650-5ff4096c-dda3-4fcc-b523-2530a68416f7.png)

**Comment by pablosnt** [comment]
Hello @genericcontributor, can you help me with that? Thank you in advance

**Comment by mcdonnnj** [comment]
@pablosnt I do not believe `interact.sh` offers HTTPS connectivity. I am only able to connect via HTTP in Firefox and `curl` has the same result:

```console
$ curl https://interact.sh
curl: (28) Failed to connect to interact.sh port 443 after 130948 ms: Connection timed out
$ curl http://interact.sh
<h1> Interactsh Server </h1>

<a href='https://github.com/projectdiscovery/interactsh'><b>Interactsh</b></a> is an open-source tool for detecting out-of-band interactions. It is a tool designed to detect vulnerabilities that cause external interactions.<br><br>

If you notice any interactions from <b>*.interact.sh</b> in your logs, it's possible that someone (internal security engineers, pen-testers, bug-bounty hunters) has been testing your application.<br><br>

You should investigate the sites where these interactions were generated from, and if a vulnerability exists, examine the root cause and take the necessary steps to mitigate the issue.
```

Do you have an example that you can connect to otherwise but are unable to connect to using this tool?

**Comment by pablosnt** [comment]
Yes, you are right. But the problem is in this line because it's using HTTPS and the default `self.server` is `interact.sh`:

https://github.com/cisagov/log4j-scanner/blob/b1903004989f629468fc93a06cb35881ba8ca412/log4-scanner/log4j-scan.py#L233

So, by default, it doesn't work.
